import type { SiteContent } from "@/types/content";

/**
 * Site-level content — DADAVAR.
 *
 * DADAVAR is a fictional firm. The phone and WhatsApp numbers are unassigned
 * placeholders on the same convention as every sibling template: `wa.me`
 * answers an unassigned number with "this link is invalid" rather than opening
 * a chat with a stranger, which is the right behaviour for a stand-in.
 *
 * What is deliberately absent, and must stay absent: any licence or bar
 * membership, any registration number, any founding year, any named person,
 * any client, any outcome. `disclaimer` is the one sentence that says, once and
 * quietly, what the site is — for a law firm that line was judged worth having
 * even though the rest of the family carries none.
 */
export const site: SiteContent = {
  brand: {
    name: "دادآور",
    latin: "DADAVAR",
    line: "دفتر حقوقی در امور تجاری: قرارداد، شرکت، اختلاف.",
  },

  seo: {
    title: "دادآور — دفتر حقوقی در امور تجاری",
    titleTemplate: "%s — دادآور",
    description:
      "دادآور دفتری حقوقی در امور تجاری است. نه حوزه‌ی کاری در سه گروه: قراردادها، شرکت‌ها، و دعاوی و حل اختلاف.",
    /** Generated by `scripts/generate-og.mjs` — a raster, because no social
     *  crawler renders an SVG share card. The left half is `o-01.jpg`. */
    ogImage: {
      src: "/media/og-card.jpg",
      alt: "در نیمه‌ی چپ، میزی بلند و خالی کنار پنجره‌ای بلند؛ در نیمه‌ی راست، نشان دادآور روی زمینه‌ی تیره",
      width: 1200,
      height: 630,
    },
  },

  pages: [
    { label: "حوزه‌های کاری", href: "/practice/" },
    { label: "یادداشت‌ها", href: "/notes/" },
    { label: "دفتر", href: "/about/" },
  ],

  contact: {
    city: "تهران",
    phone: "۰۲۱ — ۰۰۰۰ ۰۰۰۰",
    phoneHref: "+982100000000",
    whatsapp: "989000000000",
  },

  disclaimer:
    "دادآور دفتری خیالی است و این وب‌سایت نمونه‌ی یک طراحی است؛ هیچ بخشی از آن مشاوره‌ی حقوقی نیست.",

  copyrightName: "دادآور",
};
